

export const currencies = {
    AFN: { name: "Afghani", numeric: 971 },
    EUR: { name: "Euro", numeric: 978 },
    ALL: { name: "Lek", numeric: 8 },
    DZD: { name: "Algerian Dinar", numeric: 12 },
    USD: { name: "US Dollar", numeric: 840 },
    AOA: { name: "Kwanza", numeric: 973 },
    XCD: { name: "East Caribbean Dollar", numeric: 951 },
    ARS: { name: "Argentine Peso", numeric: 32 },
    AMD: { name: "Armenian Dram", numeric: 51 },
    AWG: { name: "Aruban Florin", numeric: 533 },
    AUD: { name: "Australian Dollar", numeric: 36 },
    AZN: { name: "Azerbaijan Manat", numeric: 944 },
    BSD: { name: "Bahamian Dollar", numeric: 44 },
    BHD: { name: "Bahraini Dinar", numeric: 48 },
    BDT: { name: "Taka", numeric: 50 },
    BBD: { name: "Barbados Dollar", numeric: 52 },
    BYN: { name: "Belarusian Ruble", numeric: 933 },
    BZD: { name: "Belize Dollar", numeric: 84 },
    XOF: { name: "CFA Franc BCEAO", numeric: 952 },
    BMD: { name: "Bermudian Dollar", numeric: 60 },
    INR: { name: "Indian Rupee", numeric: 356 },
    BTN: { name: "Ngultrum", numeric: 64 },
    BOB: { name: "Boliviano", numeric: 68 },
    BOV: { name: "Mvdol", numeric: 984 },
    BAM: { name: "Convertible Mark", numeric: 977 },
    BWP: { name: "Pula", numeric: 72 },
    NOK: { name: "Norwegian Krone", numeric: 578 },
    BRL: { name: "Brazilian Real", numeric: 986 },
    BND: { name: "Brunei Dollar", numeric: 96 },
    BGN: { name: "Bulgarian Lev", numeric: 975 },
    BIF: { name: "Burundi Franc", numeric: 108 },
    CVE: { name: "Cabo Verde Escudo", numeric: 132 },
    KHR: { name: "Riel", numeric: 116 },
    XAF: { name: "CFA Franc BEAC", numeric: 950 },
    CAD: { name: "Canadian Dollar", numeric: 124 },
    KYD: { name: "Cayman Islands Dollar", numeric: 136 },
    CLP: { name: "Chilean Peso", numeric: 152 },
    CLF: { name: "Unidad de Fomento", numeric: 990 },
    CNY: { name: "Yuan Renminbi", numeric: 156 },
    COP: { name: "Colombian Peso", numeric: 170 },
    COU: { name: "Unidad de Valor Real", numeric: 970 },
    KMF: { name: "Comorian Franc", numeric: 174 },
    CDF: { name: "Congolese Franc", numeric: 976 },
    NZD: { name: "New Zealand Dollar", numeric: 554 },
    CRC: { name: "Costa Rican Colon", numeric: 188 },
    HRK: { name: "Croatian Kuna", numeric: 191 },
    CUP: { name: "Cuban Peso", numeric: 192 },
    CUC: { name: "Peso Convertible", numeric: 931 },
    ANG: { name: "Netherlands Antillean Guilder", numeric: 532 },
    CZK: { name: "Czech Koruna", numeric: 203 },
    DKK: { name: "Danish Krone", numeric: 208 },
    DJF: { name: "Djibouti Franc", numeric: 262 },
    DOP: { name: "Dominican Peso", numeric: 214 },
    EGP: { name: "Egyptian Pound", numeric: 818 },
    SVC: { name: "El Salvador Colon", numeric: 222 },
    ERN: { name: "Nakfa", numeric: 232 },
    ETB: { name: "Ethiopian Birr", numeric: 230 },
    FKP: { name: "Falkland Islands Pound", numeric: 238 },
    FJD: { name: "Fiji Dollar", numeric: 242 },
    XPF: { name: "CFP Franc", numeric: 953 },
    GMD: { name: "Dalasi", numeric: 270 },
    GEL: { name: "Lari", numeric: 981 },
    GHS: { name: "Ghana Cedi", numeric: 936 },
    GIP: { name: "Gibraltar Pound", numeric: 292 },
    GTQ: { name: "Quetzal", numeric: 320 },
    GBP: { name: "Pound Sterling", numeric: 826 },
    GNF: { name: "Guinean Franc", numeric: 324 },
    GYD: { name: "Guyana Dollar", numeric: 328 },
    HTG: { name: "Gourde", numeric: 332 },
    HNL: { name: "Lempira", numeric: 340 },
    HKD: { name: "Hong Kong Dollar", numeric: 344 },
    HUF: { name: "Forint", numeric: 348 },
    ISK: { name: "Iceland Krona", numeric: 352 },
    IDR: { name: "Rupiah", numeric: 360 },
    XDR: { name: "SDR (Special Drawing Right)", numeric: 960 },
    IRR: { name: "Iranian Rial", numeric: 364 },
    IQD: { name: "Iraqi Dinar", numeric: 368 },
    ILS: { name: "New Israeli Sheqel", numeric: 376 },
    JMD: { name: "Jamaican Dollar", numeric: 388 },
    JPY: { name: "Yen", numeric: 392 },
    JOD: { name: "Jordanian Dinar", numeric: 400 },
    KZT: { name: "Tenge", numeric: 398 },
    KES: { name: "Kenyan Shilling", numeric: 404 },
    KPW: { name: "North Korean Won", numeric: 408 },
    KRW: { name: "Won", numeric: 410 },
    KWD: { name: "Kuwaiti Dinar", numeric: 414 },
    KGS: { name: "Som", numeric: 417 },
    LAK: { name: "Lao Kip", numeric: 418 },
    LBP: { name: "Lebanese Pound", numeric: 422 },
    LSL: { name: "Loti", numeric: 426 },
    ZAR: { name: "Rand", numeric: 710 },
    LRD: { name: "Liberian Dollar", numeric: 430 },
    LYD: { name: "Libyan Dinar", numeric: 434 },
    CHF: { name: "Swiss Franc", numeric: 756 },
    MOP: { name: "Pataca", numeric: 446 },
    MKD: { name: "Denar", numeric: 807 },
    MGA: { name: "Malagasy Ariary", numeric: 969 },
    MWK: { name: "Kwacha", numeric: 454 },
    MYR: { name: "Malaysian Ringgit", numeric: 458 },
    MVR: { name: "Rufiyaa", numeric: 462 },
    MRO: { name: "Ouguiya", numeric: 478 },
    MUR: { name: "Mauritius Rupee", numeric: 480 },
    XUA: { name: "ADB Unit of Account", numeric: 965 },
    MXN: { name: "Mexican Peso", numeric: 484 },
    MXV: { name: "Mexican Unidad de Inversion (UDI)", numeric: 979 },
    MDL: { name: "Moldovan Leu", numeric: 498 },
    MNT: { name: "Tugrik", numeric: 496 },
    MAD: { name: "Moroccan Dirham", numeric: 504 },
    MZN: { name: "Mozambique Metical", numeric: 943 },
    MMK: { name: "Kyat", numeric: 104 },
    NAD: { name: "Namibia Dollar", numeric: 516 },
    NPR: { name: "Nepalese Rupee", numeric: 524 },
    NIO: { name: "Cordoba Oro", numeric: 558 },
    NGN: { name: "Naira", numeric: 566 },
    OMR: { name: "Rial Omani", numeric: 512 },
    PKR: { name: "Pakistan Rupee", numeric: 586 },
    PAB: { name: "Balboa", numeric: 590 },
    PGK: { name: "Kina", numeric: 598 },
    PYG: { name: "Guarani", numeric: 600 },
    PEN: { name: "Nuevo Sol", numeric: 604 },
    PHP: { name: "Philippine Piso", numeric: 608 },
    PLN: { name: "Zloty", numeric: 985 },
    QAR: { name: "Qatari Rial", numeric: 634 },
    RON: { name: "New Romanian Leu", numeric: 946 },
    RUB: { name: "Russian Ruble", numeric: 643 },
    RWF: { name: "Rwanda Franc", numeric: 646 },
    SHP: { name: "Saint Helena Pound", numeric: 654 },
    WST: { name: "Tala", numeric: 882 },
    STD: { name: "Dobra", numeric: 678 },
    SAR: { name: "Saudi Riyal", numeric: 682 },
    RSD: { name: "Serbian Dinar", numeric: 941 },
    SCR: { name: "Seychelles Rupee", numeric: 690 },
    SLL: { name: "Leone", numeric: 694 },
    SGD: { name: "Singapore Dollar", numeric: 702 },
    XSU: { name: "Sucre", numeric: 994 },
    SBD: { name: "Solomon Islands Dollar", numeric: 90 },
    SOS: { name: "Somali Shilling", numeric: 706 },
    SSP: { name: "South Sudanese Pound", numeric: 728 },
    LKR: { name: "Sri Lanka Rupee", numeric: 144 },
    SDG: { name: "Sudanese Pound", numeric: 938 },
    SRD: { name: "Surinam Dollar", numeric: 968 },
    SZL: { name: "Lilangeni", numeric: 748 },
    SEK: { name: "Swedish Krona", numeric: 752 },
    CHE: { name: "WIR Euro", numeric: 947 },
    CHW: { name: "WIR Franc", numeric: 948 },
    SYP: { name: "Syrian Pound", numeric: 760 },
    TWD: { name: "New Taiwan Dollar", numeric: 901 },
    TJS: { name: "Somoni", numeric: 972 },
    TZS: { name: "Tanzanian Shilling", numeric: 834 },
    THB: { name: "Baht", numeric: 764 },
    TOP: { name: "Pa’anga", numeric: 776 },
    TTD: { name: "Trinidad and Tobago Dollar", numeric: 780 },
    TND: { name: "Tunisian Dinar", numeric: 788 },
    TRY: { name: "New Turkish Lira", numeric: 949 },
    TMT: { name: "Turkmenistan New Manat", numeric: 934 },
    UGX: { name: "Uganda Shilling", numeric: 800 },
    UAH: { name: "Hryvnia", numeric: 980 },
    AED: { name: "UAE Dirham", numeric: 784 },
    USN: { name: "US Dollar (Next day)", numeric: 997 },
    UYU: { name: "Peso Uruguayo", numeric: 858 },
    UYI: { name: "Uruguay Peso en Unidades Indexadas (URUIURUI)", numeric: 940 },
    UZS: { name: "Uzbekistan Sum", numeric: 860 },
    VUV: { name: "Vatu", numeric: 548 },
    VEF: { name: "Bolivar", numeric: 937 },
    VND: { name: "Dong", numeric: 704 },
    YER: { name: "Yemeni Rial", numeric: 886 },
    ZMW: { name: "Zambian Kwacha", numeric: 967 },
    ZWL: { name: "Zimbabwe Dollar", numeric: 932 },
    XBA: { name: "Bond Markets Unit European Composite Unit (EURCO)", numeric: 955 },
    XBB: { name: "Bond Markets Unit European Monetary Unit (E.M.U.-6)", numeric: 956 },
    XBC: { name: "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)", numeric: 957 },
    XBD: { name: "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)", numeric: 958 },
    XTS: { name: "Codes specifically reserved for testing purposes", numeric: 963 },
    XXX: { name: "The codes assigned for transactions where no currency is involved", numeric: 999 },
    XAU: { name: "Gold", numeric: 959 },
    XPD: { name: "Palladium", numeric: 964 },
    XPT: { name: "Platinum", numeric: 962 },
    XAG: { name: "Silver", numeric: 961 },
    AFA: { name: "Afghani", numeric: 4 },
    FIM: { name: "Markka", numeric: 246 },
    ADP: { name: "Andorran Peseta", numeric: 20 },
    ESP: { name: "Spanish Peseta", numeric: 724 },
    FRF: { name: "French Franc", numeric: 250 },
    AON: { name: "New Kwanza", numeric: 24 },
    AOR: { name: "Kwanza Reajustado", numeric: 982 },
    ARA: { name: "Austral", numeric: 32 },
    ARP: { name: "Peso Argentino", numeric: 32 },
    RUR: { name: "Russian Ruble", numeric: 810 },
    ATS: { name: "Schilling", numeric: 40 },
    AYM: { name: "Azerbaijan Manat", numeric: 945 },
    AZM: { name: "Azerbaijanian Manat", numeric: 31 },
    BYR: { name: "Belarusian Ruble", numeric: 974 },
    BYB: { name: "Belarusian Ruble", numeric: 112 },
    BEC: { name: "Convertible Franc", numeric: 993 },
    BEF: { name: "Belgian Franc", numeric: 56 },
    BEL: { name: "Financial Franc", numeric: 992 },
    BAD: { name: "Dinar", numeric: 70 },
    BRC: { name: "Cruzado", numeric: 76 },
    BRE: { name: "Cruzeiro", numeric: 76 },
    BRN: { name: "New Cruzado", numeric: 76 },
    BRR: { name: "Cruzeiro Real", numeric: 987 },
    BGL: { name: "Lev", numeric: 100 },
    HRD: { name: "Croatian Dinar", numeric: 191 },
    CYP: { name: "Cyprus Pound", numeric: 196 },
    CSK: { name: "Koruna", numeric: 200 },
    ECS: { name: "Sucre", numeric: 218 },
    ECV: { name: "Unidad de Valor Constante (UVC)", numeric: 983 },
    GQE: { name: "Ekwele", numeric: 226 },
    EEK: { name: "Kroon", numeric: 233 },
    XEU: { name: "European Currency Unit (E.C.U)", numeric: 954 },
    GEK: { name: "Georgian Coupon", numeric: 268 },
    DDM: { name: "Mark der DDR", numeric: 278 },
    DEM: { name: "Deutsche Mark", numeric: 276 },
    GHC: { name: "Cedi", numeric: 288 },
    GHP: { name: "Ghana Cedi", numeric: 939 },
    GRD: { name: "Drachma", numeric: 300 },
    GWP: { name: "Guinea-Bissau Peso", numeric: 624 },
    ITL: { name: "Italian Lira", numeric: 380 },
    IEP: { name: "Irish Pound", numeric: 372 },
    LVL: { name: "Latvian Lats", numeric: 428 },
    LVR: { name: "Latvian Ruble", numeric: 428 },
    ZAL: { name: "Financial Rand", numeric: 991 },
    LTL: { name: "Lithuanian Litas", numeric: 440 },
    LTT: { name: "Talonas", numeric: 440 },
    LUC: { name: "Luxembourg Convertible Franc", numeric: 989 },
    LUF: { name: "Luxembourg Franc", numeric: 442 },
    LUL: { name: "Luxembourg Financial Franc", numeric: 988 },
    MGF: { name: "Malagasy Franc", numeric: 450 },
    MLF: { name: "Mali Franc", numeric: 466 },
    MTL: { name: "Maltese Lira", numeric: 470 },
    MZM: { name: "Mozambique Metical", numeric: 508 },
    NLG: { name: "Netherlands Guilder", numeric: 528 },
    PEI: { name: "Inti", numeric: 604 },
    PES: { name: "Sol", numeric: 604 },
    PLZ: { name: "Zloty", numeric: 616 },
    PTE: { name: "Portuguese Escudo", numeric: 620 },
    ROL: { name: "Old Leu", numeric: 642 },
    CSD: { name: "Serbian Dinar", numeric: 891 },
    SKK: { name: "Slovak Koruna", numeric: 703 },
    SIT: { name: "Tolar", numeric: 705 },
    ESA: { name: "Spanish Peseta", numeric: 996 },
    SDD: { name: "Sudanese Dinar", numeric: 736 },
    SRG: { name: "Surinam Guilder", numeric: 740 },
    CHC: { name: "WIR Franc (for electronic)", numeric: 948 },
    TJR: { name: "Tajik Ruble", numeric: 762 },
    TPE: { name: "Timor Escudo", numeric: 626 },
    TRL: { name: "Old Turkish Lira", numeric: 792 },
    TMM: { name: "Turkmenistan Manat", numeric: 795 },
    UAK: { name: "Karbovanet", numeric: 804 },
    USS: { name: "US Dollar (Same day)", numeric: 998 },
    VEB: { name: "Bolivar", numeric: 862 },
    YDD: { name: "Yemeni Dinar", numeric: 720 },
    YUM: { name: "New Dinar", numeric: 891 },
    YUN: { name: "Yugoslavian Dinar", numeric: 890 },
    ZRN: { name: "New Zaire", numeric: 180 },
    ZRZ: { name: "Zaire", numeric: 180 },
    ZMK: { name: "Zambian Kwacha", numeric: 894 },
    ZWD: { name: "Zimbabwe Dollar", numeric: 716 },
    ZWN: { name: "Zimbabwe Dollar (new)", numeric: 942 },
    ZWR: { name: "Zimbabwe Dollar", numeric: 935 },
};

export type Currency = string
// export type Currency = "AFN" | "EUR" | "ALL" | "DZD" | "USD" | "AOA" | "XCD" | "ARS" | "AMD" | "AWG" | "AUD" | "AZN" | "BSD" | "BHD" | "BDT" | "BBD" | "BYN" | "BZD" | "XOF" | "BMD" | "INR" | "BTN" | "BOB" | "BOV" | "BAM" |
//     "BWP" | "NOK" | "BRL" | "BND" | "BGN" | "BIF" | "CVE" | "KHR" | "XAF" | "CAD" | "KYD" | "CLP" | "CLF" | "CNY" | "COP" | "COU" | "KMF" | "CDF" | "NZD" | "CRC" | "HRK" | "CUP" | "CUC" | "ANG" | "CZK" | "DKK" | "DJF" | "DOP"
//     | "EGP" | "SVC" | "ERN" | "ETB" | "FKP" | "FJD" | "XPF" | "GMD" | "GEL" | "GHS" | "GIP" | "GTQ" | "GBP" | "GNF" | "GYD" | "HTG" | "HNL" | "HKD" | "HUF" |
//     "ISK" | "IDR" | "XDR" | "IRR" | "IQD" | "ILS" | "JMD" | "JPY" | "JOD" | "KZT" | "KES" | "KPW" | "KRW" | "KWD" | "KGS" | "LAK" | "LBP" | "LSL" | "ZAR" | "LRD" | "LYD" | "CHF" | "MOP" | "MKD" | "MGA" | "MWK" | "MYR" | "MVR"
//     | "MRO" | "MUR" | "XUA" | "MXN" | "MXV" | "MDL" | "MNT" | "MAD" | "MZN" | "MMK" | "NAD" | "NPR" | "NIO" | "NGN" | "OMR" | "PKR" | "PAB" | "PGK" | "PYG" | "PEN" | "PHP" | "PLN" | "QAR" | "RON" | "RUB" | "RWF" | "SHP" | "WST"
//     | "STD" | "SAR" | "RSD" | "SCR" | "SLL" | "SGD" | "XSU" | "SBD" | "SOS" | "SSP" | "LKR" | "SDG" | "SRD" | "SZL" | "SEK" | "CHE" | "CHW" | "SYP" | "TWD" | "TJS" | "TZS" | "THB" | "TOP" | "TTD" | "TND" | "TRY" | "TMT" | "UGX"
//     | "UAH" | "AED" | "USN" | "UYU" | "UYI" | "UZS" | "VUV" | "VEF" | "VND" | "YER" | "ZMW" | "ZWL" | "XBA" | "XBB" | "XBC" | "XBD" | "XTS" | "XXX" | "XAU" | "XPD" | "XPT" | "XAG" | "AFA" | "FIM" | "ADP" | "ESP" | "FRF" | "AON"
//     | "AOR" | "ARA" | "ARP" | "RUR" | "ATS" | "AYM" | "AZM" | "BYR" | "BYB" | "BEC" | "BEF" | "BEL" | "BAD" | "BRC" | "BRE" | "BRN" | "BRR" | "BGL" | "HRD" | "CYP" | "CSK" | "ECS" | "ECV" | "GQE" | "EEK" | "XEU" | "GEK" | "DDM"
//     | "DEM" | "GHC" | "GHP" | "GRD" | "GWP" | "ITL" | "IEP" | "LVL" | "LVR" | "ZAL" | "LTL" | "LTT" | "LUC" | "LUF" | "LUL" | "MGF" | "MLF" | "MTL" | "MZM" | "NLG" | "PEI" | "PES" | "PLZ" | "PTE" | "ROL" | "CSD" | "SKK" | "SIT"
//     | "ESA" | "SDD" | "SRG" | "CHC" | "TJR" | "TPE" | "TRL" | "TMM" | "UAK" | "USS" | "VEB" | "YDD" | "YUM" | "YUN" | "ZRN" | "ZRZ" | "ZMK" | "ZWD" | "ZWN" | "ZWR" | "BNB" | "COIN" | "ISKT";